version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pet_db
      - POSTGRES_USER=pet_user
      - POSTGRES_PASSWORD=pet_pass

  vet-clinic:
    image: akhnazarova/vet-clinic
    container_name: vet-clinic
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_USER=pet_user
      - SPRING_DATASOURCE_PASSWORD=pet_pass
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pet_db
    ports:
      - 8080:8080